# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lille My Design
email: lillemy@mail.com

description: >- # this means to ignore newlines until "baseurl:"
  A little designer with big dreams. Determined but curious, fearless but friendly.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: minima
theme: jekyll-theme-portfolyou-aho # using local theme as git submodule

#remote_theme: aho-opensource/jekyll-theme-portfolyou-aho

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
#theme: minima
#theme: minima
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - themes/


### Collections ###
collections:
  posts:
    output: true
    permalink: /blog/:title
  projects:
    output: true
    permalink: /projects/:name
  # etc


################################################################################
# theme variables
#

author:
  name              : Lille My
  image             : https://www.creativefabrica.com/wp-content/uploads/2023/05/01/Moomin-Little-My-Graphic-Graphics-68564846-1.jpg

  # social connections. 
  # you can define your own in _data/social_media.yml, see documentation
  email             : lillemy50@mumindalen.org
  github            : lillemy50
  pinterest         : lillemy50
  instagram         : lillemy50
# linkedin          : lillemy50
# behance           : lillemy50
# dribbble          : lillemy50
# gitlab            : lillemy50
# kaggle            : lillemy50
# medium            : lillemy50
# soundcloud        : lillemy50
# spotify           : lillemy50
# stackoverflow     : lillemy50
# twitch            : lillemy50
# twitter           : lillemy50
# facebook          : lillemy50
# vimeo             : lillemy50
# youtube           : lillemy50
# keybase           : lillemy50

  # TODO: page:, caption: 
navbar:
    toggle_theme: false
    items:
      - page: pages/about.md
      - page: pages/blog.html
      - page: pages/tags.html
        caption: My Tags
      - page: pages/404.html
        caption: ":no_entry:"

# Opens external URLs in new tab (works for posts, projects and navbar only)
external_new_tab    : true                    


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id
